version: '2'
services:
  magento2_nginx:
    container_name: MAGENTO2_nginx
    image: nginx:stable
    volumes:
      - ./app/magento2:/srv/magento2
      - ./mount/nginx/magento.conf:/etc/nginx/conf.d/default.conf
    network_mode: "DOCKER_network"
    labels:
      - "traefik.backend=MAGENTO2_nginx"
      - "traefik.port=80"
      - "traefik.frontend.rule=Host:magento.qwerty.re" # Comment this when enable varnish
      - "traefik.docker.network=DOCKER_network"
    depends_on:
      - magento2_php
  magento2_php:
    container_name: MAGENTO2_php
    image: bmxmale/magento2-php:2.2
    volumes:
      - ./app/magento2:/srv/magento2
      - ./mount/ssmtp.conf:/etc/ssmtp/ssmtp.conf
#    environment:
#      - PHP_USER=1000
#      - PHP_GROUP=1000
    network_mode: "DOCKER_network"
#  magento2_varnish:
#    container_name: magento2_varnish
#    image: bmxmale/docker-magento-varnish:5.2.1
#    volumes:
#      - ./mount/varnish/varnish.vcl:/etc/varnish/default.vcl
#    environment:
#      - DEFAULT_VCL=0
#    network_mode: "DOCKER_network"
#    labels:
#      - "traefik.backend=magento2_varnish"
#      - "traefik.port=80"
#      - "traefik.frontend.rule=Host:magento.qwerty.re"
#      - "traefik.docker.network=DOCKER_network"
#    depends_on:
#      - magento2_nginx